#ifndef C_BINDINGS_ACC_HASH_SET_H
#define C_BINDINGS_ACC_HASH_SET_H

/* Generated with cbindgen:0.29.2 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>


typedef struct CAccumulativeHashSetU64 CAccumulativeHashSetU64;

typedef unsigned short CBool;

typedef unsigned int CItem;

void free_hash_set(struct CAccumulativeHashSetU64 *ptr);

CBool hash_set_backtrack(struct CAccumulativeHashSetU64 *ptr);

CBool hash_set_contains_path_to(const struct CAccumulativeHashSetU64 *ptr, unsigned long state);

unsigned long hash_set_state(const struct CAccumulativeHashSetU64 *ptr);

CBool hash_set_transverse_to(struct CAccumulativeHashSetU64 *ptr, CItem element);

CBool hash_set_visit_and_backtrack(struct CAccumulativeHashSetU64 *ptr);

unsigned long hash_set_visited_count(const struct CAccumulativeHashSetU64 *ptr);

struct CAccumulativeHashSetU64 *new_hash_set(void);

#endif  /* C_BINDINGS_ACC_HASH_SET_H */
