#ifndef TYPES_STATUS_H
#define TYPES_STATUS_H

typedef enum {
    NO_SOLUTION = -1,
    SUCCESS = 0,
    PARSE_INVALID_BRACKETS = 1,
    PARSE_INVALID_NUMBER = 2,
    PARSE_INVALID_INDICATOR = 3,
    PARSE_EMPTY_BUFFER = 4,
    PARSE_TARGET_OVERFLOWS = 5,
    PARSE_DIMENSIONS_OUT_OF_RANGE = 8,
    PARSE_LINE_MISSING_COMPONENTS = 9,
    MISMATCHED_DIMENSIONS = 16,
    MISMATCHED_BUTTON_COUNT = 17,
    BUTTON_NOT_FOUND = 18,
    INSUFFICIENT_CAPACITY = 32,
    VECTOR_UNDERFLOW = 33,
    DISTANCE_UNDERFLOW = 34,
    VECTOR_OVERFLOW = 35,
    PRESS_OVERFLOW = 36,
    BALANCING_IMPOSSIBLE = 64,
    INDIVISIBLE_VALUE = 65,
    UNDETERMINED = 65534, // A placeholder status to say that "more work needed"
    NOT_IMPLEMENTED = 65535
} ExecutionStatus;

#endif
