name: C

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        requirements:
        - folder: "aoc-2025-02-c"
          need-c-bindgen: false
        - folder: "aoc-2025-03-c"
          need-c-bindgen: false
        - folder: "aoc-2025-05-c"
          need-c-bindgen: false
        - folder: "aoc-2025-10-c"
          need-c-bindgen: true

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up C environment
      run: sudo apt update && sudo apt install build-essential
    - name: Set up CBindgen
      if: matrix.requirements.need-c-bindgen == true
      run: |
        cargo install cbindgen
    - name: Run tests
      working-directory: ./${{ matrix.requirements.folder }}
      run: FLAGS="VERBOSE UNIT_TEST" make test
